<?php

/**
 * BaseArchive
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $edition
 * @property string $link_to
 * @property integer $image_id
 * @property Image $Image
 * @property Doctrine_Collection $ArchiveGallery
 * @property Doctrine_Collection $ArchiveExhibitionImage
 * @property Doctrine_Collection $ArchiveExhibitionVideo
 * @property Doctrine_Collection $ArchiveExhibitionAudio
 * 
 * @method string              getEdition()                Returns the current record's "edition" value
 * @method string              getLinkTo()                 Returns the current record's "link_to" value
 * @method integer             getImageId()                Returns the current record's "image_id" value
 * @method Image               getImage()                  Returns the current record's "Image" value
 * @method Doctrine_Collection getArchiveGallery()         Returns the current record's "ArchiveGallery" collection
 * @method Doctrine_Collection getArchiveExhibitionImage() Returns the current record's "ArchiveExhibitionImage" collection
 * @method Doctrine_Collection getArchiveExhibitionVideo() Returns the current record's "ArchiveExhibitionVideo" collection
 * @method Doctrine_Collection getArchiveExhibitionAudio() Returns the current record's "ArchiveExhibitionAudio" collection
 * @method Archive             setEdition()                Sets the current record's "edition" value
 * @method Archive             setLinkTo()                 Sets the current record's "link_to" value
 * @method Archive             setImageId()                Sets the current record's "image_id" value
 * @method Archive             setImage()                  Sets the current record's "Image" value
 * @method Archive             setArchiveGallery()         Sets the current record's "ArchiveGallery" collection
 * @method Archive             setArchiveExhibitionImage() Sets the current record's "ArchiveExhibitionImage" collection
 * @method Archive             setArchiveExhibitionVideo() Sets the current record's "ArchiveExhibitionVideo" collection
 * @method Archive             setArchiveExhibitionAudio() Sets the current record's "ArchiveExhibitionAudio" collection
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArchive extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('archive');
        $this->hasColumn('edition', 'string', 4, array(
             'type' => 'string',
             'length' => 4,
             ));
        $this->hasColumn('link_to', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('image_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Image', array(
             'local' => 'image_id',
             'foreign' => 'id'));

        $this->hasMany('ArchiveGallery', array(
             'local' => 'id',
             'foreign' => 'archive_id'));

        $this->hasMany('ArchiveExhibitionImage', array(
             'local' => 'id',
             'foreign' => 'archive_id'));

        $this->hasMany('ArchiveExhibitionVideo', array(
             'local' => 'id',
             'foreign' => 'archive_id'));

        $this->hasMany('ArchiveExhibitionAudio', array(
             'local' => 'id',
             'foreign' => 'archive_id'));
    }
}