<?php

/**
 * BaseSubpage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $event
 * @property string $content
 * @property Doctrine_Collection $StaticContentSubpage
 * 
 * @method string              getName()                 Returns the current record's "name" value
 * @method string              getEvent()                Returns the current record's "event" value
 * @method string              getContent()              Returns the current record's "content" value
 * @method Doctrine_Collection getStaticContentSubpage() Returns the current record's "StaticContentSubpage" collection
 * @method Subpage             setName()                 Sets the current record's "name" value
 * @method Subpage             setEvent()                Sets the current record's "event" value
 * @method Subpage             setContent()              Sets the current record's "content" value
 * @method Subpage             setStaticContentSubpage() Sets the current record's "StaticContentSubpage" collection
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubpage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subpage');
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'unique' => true,
             'length' => 120,
             ));
        $this->hasColumn('event', 'string', 120, array(
             'type' => 'string',
             'unique' => true,
             'length' => 120,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('StaticContentSubpage', array(
             'local' => 'id',
             'foreign' => 'subpage_id'));
    }
}