<?php

/**
 * BaseStaticContentSubpage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $subpage_id
 * @property string $name
 * @property string $title
 * @property string $content
 * @property boolean $is_module
 * @property Subpage $Subpage
 * 
 * @method integer              getSubpageId()  Returns the current record's "subpage_id" value
 * @method string               getName()       Returns the current record's "name" value
 * @method string               getTitle()      Returns the current record's "title" value
 * @method string               getContent()    Returns the current record's "content" value
 * @method boolean              getIsModule()   Returns the current record's "is_module" value
 * @method Subpage              getSubpage()    Returns the current record's "Subpage" value
 * @method StaticContentSubpage setSubpageId()  Sets the current record's "subpage_id" value
 * @method StaticContentSubpage setName()       Sets the current record's "name" value
 * @method StaticContentSubpage setTitle()      Sets the current record's "title" value
 * @method StaticContentSubpage setContent()    Sets the current record's "content" value
 * @method StaticContentSubpage setIsModule()   Sets the current record's "is_module" value
 * @method StaticContentSubpage setSubpage()    Sets the current record's "Subpage" value
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStaticContentSubpage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('static_content_subpage');
        $this->hasColumn('subpage_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('title', 'string', 512, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 512,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('is_module', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Subpage', array(
             'local' => 'subpage_id',
             'foreign' => 'id'));
    }
}