<?php

/**
 * BaseLayoutImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $filename
 * @property integer $order_nr
 * 
 * @method string      getFilename() Returns the current record's "filename" value
 * @method integer     getOrderNr()  Returns the current record's "order_nr" value
 * @method LayoutImage setFilename() Sets the current record's "filename" value
 * @method LayoutImage setOrderNr()  Sets the current record's "order_nr" value
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLayoutImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('layout_image');
        $this->hasColumn('filename', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('order_nr', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}