<?php

/**
 * BaseVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $filename
 * @property Doctrine_Collection $ArchiveExhibitionVideo
 * 
 * @method string              getFilename()               Returns the current record's "filename" value
 * @method Doctrine_Collection getArchiveExhibitionVideo() Returns the current record's "ArchiveExhibitionVideo" collection
 * @method Video               setFilename()               Sets the current record's "filename" value
 * @method Video               setArchiveExhibitionVideo() Sets the current record's "ArchiveExhibitionVideo" collection
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVideo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('video');
        $this->hasColumn('filename', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ArchiveExhibitionVideo', array(
             'local' => 'id',
             'foreign' => 'video_id'));
    }
}