<?php

/**
 * BaseRegistrationForm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $is_group
 * @property string $name
 * @property string $my_email
 * @property string $organization_name
 * @property string $street
 * @property string $postal_code
 * @property string $locality
 * @property string $voivodeship
 * @property string $phone_number
 * @property string $fax
 * @property string $organization_email
 * @property string $internet_page
 * @property string $NIP
 * @property boolean $agreement1
 * @property integer $number_of_participants
 * @property integer $fee_number
 * @property string $fee_total
 * @property string $fac_name
 * @property string $fac_address
 * @property string $fac_NIP
 * @property boolean $accommodation
 * @property boolean $participation_1
 * @property boolean $participants_1
 * @property boolean $participation_2
 * @property boolean $participants_2
 * @property boolean $participation_3
 * @property boolean $participants_3
 * @property boolean $participation_4
 * @property boolean $participants_4
 * @property boolean $participation_5
 * @property boolean $participants_5
 * @property boolean $participation_6
 * @property boolean $participants_6
 * @property boolean $participation_7
 * @property boolean $participants_7
 * @property boolean $participation_8
 * @property boolean $participants_8
 * @property boolean $participation_9
 * @property boolean $participants_9
 * @property boolean $participation_10
 * @property boolean $participants_10
 * @property boolean $participation_11
 * @property boolean $participants_11
 * @property boolean $participation_12
 * @property boolean $participants_12
 * @property boolean $participation_13
 * @property boolean $participants_13
 * @property boolean $participation_14
 * @property boolean $participants_14
 * @property boolean $participation_15
 * @property boolean $participants_15
 * @property boolean $agreement2
 * 
 * @method boolean          getIsGroup()                Returns the current record's "is_group" value
 * @method string           getName()                   Returns the current record's "name" value
 * @method string           getMyEmail()                Returns the current record's "my_email" value
 * @method string           getOrganizationName()       Returns the current record's "organization_name" value
 * @method string           getStreet()                 Returns the current record's "street" value
 * @method string           getPostalCode()             Returns the current record's "postal_code" value
 * @method string           getLocality()               Returns the current record's "locality" value
 * @method string           getVoivodeship()            Returns the current record's "voivodeship" value
 * @method string           getPhoneNumber()            Returns the current record's "phone_number" value
 * @method string           getFax()                    Returns the current record's "fax" value
 * @method string           getOrganizationEmail()      Returns the current record's "organization_email" value
 * @method string           getInternetPage()           Returns the current record's "internet_page" value
 * @method string           getNIP()                    Returns the current record's "NIP" value
 * @method boolean          getAgreement1()             Returns the current record's "agreement1" value
 * @method integer          getNumberOfParticipants()   Returns the current record's "number_of_participants" value
 * @method integer          getFeeNumber()              Returns the current record's "fee_number" value
 * @method string           getFeeTotal()               Returns the current record's "fee_total" value
 * @method string           getFacName()                Returns the current record's "fac_name" value
 * @method string           getFacAddress()             Returns the current record's "fac_address" value
 * @method string           getFacNIP()                 Returns the current record's "fac_NIP" value
 * @method boolean          getAccommodation()          Returns the current record's "accommodation" value
 * @method boolean          getParticipation1()         Returns the current record's "participation_1" value
 * @method boolean          getParticipants1()          Returns the current record's "participants_1" value
 * @method boolean          getParticipation2()         Returns the current record's "participation_2" value
 * @method boolean          getParticipants2()          Returns the current record's "participants_2" value
 * @method boolean          getParticipation3()         Returns the current record's "participation_3" value
 * @method boolean          getParticipants3()          Returns the current record's "participants_3" value
 * @method boolean          getParticipation4()         Returns the current record's "participation_4" value
 * @method boolean          getParticipants4()          Returns the current record's "participants_4" value
 * @method boolean          getParticipation5()         Returns the current record's "participation_5" value
 * @method boolean          getParticipants5()          Returns the current record's "participants_5" value
 * @method boolean          getParticipation6()         Returns the current record's "participation_6" value
 * @method boolean          getParticipants6()          Returns the current record's "participants_6" value
 * @method boolean          getParticipation7()         Returns the current record's "participation_7" value
 * @method boolean          getParticipants7()          Returns the current record's "participants_7" value
 * @method boolean          getParticipation8()         Returns the current record's "participation_8" value
 * @method boolean          getParticipants8()          Returns the current record's "participants_8" value
 * @method boolean          getParticipation9()         Returns the current record's "participation_9" value
 * @method boolean          getParticipants9()          Returns the current record's "participants_9" value
 * @method boolean          getParticipation10()        Returns the current record's "participation_10" value
 * @method boolean          getParticipants10()         Returns the current record's "participants_10" value
 * @method boolean          getParticipation11()        Returns the current record's "participation_11" value
 * @method boolean          getParticipants11()         Returns the current record's "participants_11" value
 * @method boolean          getParticipation12()        Returns the current record's "participation_12" value
 * @method boolean          getParticipants12()         Returns the current record's "participants_12" value
 * @method boolean          getParticipation13()        Returns the current record's "participation_13" value
 * @method boolean          getParticipants13()         Returns the current record's "participants_13" value
 * @method boolean          getParticipation14()        Returns the current record's "participation_14" value
 * @method boolean          getParticipants14()         Returns the current record's "participants_14" value
 * @method boolean          getParticipation15()        Returns the current record's "participation_15" value
 * @method boolean          getParticipants15()         Returns the current record's "participants_15" value
 * @method boolean          getAgreement2()             Returns the current record's "agreement2" value
 * @method RegistrationForm setIsGroup()                Sets the current record's "is_group" value
 * @method RegistrationForm setName()                   Sets the current record's "name" value
 * @method RegistrationForm setMyEmail()                Sets the current record's "my_email" value
 * @method RegistrationForm setOrganizationName()       Sets the current record's "organization_name" value
 * @method RegistrationForm setStreet()                 Sets the current record's "street" value
 * @method RegistrationForm setPostalCode()             Sets the current record's "postal_code" value
 * @method RegistrationForm setLocality()               Sets the current record's "locality" value
 * @method RegistrationForm setVoivodeship()            Sets the current record's "voivodeship" value
 * @method RegistrationForm setPhoneNumber()            Sets the current record's "phone_number" value
 * @method RegistrationForm setFax()                    Sets the current record's "fax" value
 * @method RegistrationForm setOrganizationEmail()      Sets the current record's "organization_email" value
 * @method RegistrationForm setInternetPage()           Sets the current record's "internet_page" value
 * @method RegistrationForm setNIP()                    Sets the current record's "NIP" value
 * @method RegistrationForm setAgreement1()             Sets the current record's "agreement1" value
 * @method RegistrationForm setNumberOfParticipants()   Sets the current record's "number_of_participants" value
 * @method RegistrationForm setFeeNumber()              Sets the current record's "fee_number" value
 * @method RegistrationForm setFeeTotal()               Sets the current record's "fee_total" value
 * @method RegistrationForm setFacName()                Sets the current record's "fac_name" value
 * @method RegistrationForm setFacAddress()             Sets the current record's "fac_address" value
 * @method RegistrationForm setFacNIP()                 Sets the current record's "fac_NIP" value
 * @method RegistrationForm setAccommodation()          Sets the current record's "accommodation" value
 * @method RegistrationForm setParticipation1()         Sets the current record's "participation_1" value
 * @method RegistrationForm setParticipants1()          Sets the current record's "participants_1" value
 * @method RegistrationForm setParticipation2()         Sets the current record's "participation_2" value
 * @method RegistrationForm setParticipants2()          Sets the current record's "participants_2" value
 * @method RegistrationForm setParticipation3()         Sets the current record's "participation_3" value
 * @method RegistrationForm setParticipants3()          Sets the current record's "participants_3" value
 * @method RegistrationForm setParticipation4()         Sets the current record's "participation_4" value
 * @method RegistrationForm setParticipants4()          Sets the current record's "participants_4" value
 * @method RegistrationForm setParticipation5()         Sets the current record's "participation_5" value
 * @method RegistrationForm setParticipants5()          Sets the current record's "participants_5" value
 * @method RegistrationForm setParticipation6()         Sets the current record's "participation_6" value
 * @method RegistrationForm setParticipants6()          Sets the current record's "participants_6" value
 * @method RegistrationForm setParticipation7()         Sets the current record's "participation_7" value
 * @method RegistrationForm setParticipants7()          Sets the current record's "participants_7" value
 * @method RegistrationForm setParticipation8()         Sets the current record's "participation_8" value
 * @method RegistrationForm setParticipants8()          Sets the current record's "participants_8" value
 * @method RegistrationForm setParticipation9()         Sets the current record's "participation_9" value
 * @method RegistrationForm setParticipants9()          Sets the current record's "participants_9" value
 * @method RegistrationForm setParticipation10()        Sets the current record's "participation_10" value
 * @method RegistrationForm setParticipants10()         Sets the current record's "participants_10" value
 * @method RegistrationForm setParticipation11()        Sets the current record's "participation_11" value
 * @method RegistrationForm setParticipants11()         Sets the current record's "participants_11" value
 * @method RegistrationForm setParticipation12()        Sets the current record's "participation_12" value
 * @method RegistrationForm setParticipants12()         Sets the current record's "participants_12" value
 * @method RegistrationForm setParticipation13()        Sets the current record's "participation_13" value
 * @method RegistrationForm setParticipants13()         Sets the current record's "participants_13" value
 * @method RegistrationForm setParticipation14()        Sets the current record's "participation_14" value
 * @method RegistrationForm setParticipants14()         Sets the current record's "participants_14" value
 * @method RegistrationForm setParticipation15()        Sets the current record's "participation_15" value
 * @method RegistrationForm setParticipants15()         Sets the current record's "participants_15" value
 * @method RegistrationForm setAgreement2()             Sets the current record's "agreement2" value
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistrationForm extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registration_form');
        $this->hasColumn('is_group', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('my_email', 'string', 120, array(
             'type' => 'string',
             'email' => true,
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('organization_name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('street', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('postal_code', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('locality', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('voivodeship', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('phone_number', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('fax', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('organization_email', 'string', 120, array(
             'type' => 'string',
             'email' => true,
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('internet_page', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('NIP', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('agreement1', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('number_of_participants', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fee_number', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fee_total', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('fac_name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('fac_address', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('fac_NIP', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('accommodation', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_1', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_1', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_2', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_2', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_3', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_3', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_4', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_4', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_5', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_5', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_6', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_6', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_7', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_7', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_8', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_8', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_9', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_9', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_10', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_10', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_11', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_11', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_12', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_12', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_13', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_13', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_14', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_14', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participation_15', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('participants_15', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('agreement2', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}