<?php

/**
 * BasePicnicPlan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $place
 * @property string $content
 * @property integer $image_id
 * @property Image $Image
 * 
 * @method string     getName()     Returns the current record's "name" value
 * @method string     getPlace()    Returns the current record's "place" value
 * @method string     getContent()  Returns the current record's "content" value
 * @method integer    getImageId()  Returns the current record's "image_id" value
 * @method Image      getImage()    Returns the current record's "Image" value
 * @method PicnicPlan setName()     Sets the current record's "name" value
 * @method PicnicPlan setPlace()    Sets the current record's "place" value
 * @method PicnicPlan setContent()  Sets the current record's "content" value
 * @method PicnicPlan setImageId()  Sets the current record's "image_id" value
 * @method PicnicPlan setImage()    Sets the current record's "Image" value
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePicnicPlan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('picnic_plan');
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('place', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('image_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Image', array(
             'local' => 'image_id',
             'foreign' => 'id'));
    }
}