<?php

/**
 * BaseAudio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $filename
 * @property Doctrine_Collection $ArchiveExhibitionAudio
 * 
 * @method string              getFilename()               Returns the current record's "filename" value
 * @method Doctrine_Collection getArchiveExhibitionAudio() Returns the current record's "ArchiveExhibitionAudio" collection
 * @method Audio               setFilename()               Sets the current record's "filename" value
 * @method Audio               setArchiveExhibitionAudio() Sets the current record's "ArchiveExhibitionAudio" collection
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAudio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('audio');
        $this->hasColumn('filename', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ArchiveExhibitionAudio', array(
             'local' => 'id',
             'foreign' => 'audio_id'));
    }
}