<?php

/**
 * BaseLogotype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $filename
 * 
 * @method string   getFilename() Returns the current record's "filename" value
 * @method Logotype setFilename() Sets the current record's "filename" value
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLogotype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('logotype');
        $this->hasColumn('filename', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}