<?php

/**
 * BasePicnicParticipant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $picnic_participant_image_id
 * @property string $content
 * @property integer $order_nr
 * @property PicnicParticipantImage $PicnicParticipantImage
 * 
 * @method integer                getPicnicParticipantImageId()    Returns the current record's "picnic_participant_image_id" value
 * @method string                 getContent()                     Returns the current record's "content" value
 * @method integer                getOrderNr()                     Returns the current record's "order_nr" value
 * @method PicnicParticipantImage getPicnicParticipantImage()      Returns the current record's "PicnicParticipantImage" value
 * @method PicnicParticipant      setPicnicParticipantImageId()    Sets the current record's "picnic_participant_image_id" value
 * @method PicnicParticipant      setContent()                     Sets the current record's "content" value
 * @method PicnicParticipant      setOrderNr()                     Sets the current record's "order_nr" value
 * @method PicnicParticipant      setPicnicParticipantImage()      Sets the current record's "PicnicParticipantImage" value
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePicnicParticipant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('picnic_participant');
        $this->hasColumn('picnic_participant_image_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('order_nr', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PicnicParticipantImage', array(
             'local' => 'picnic_participant_image_id',
             'foreign' => 'id'));
    }
}