<?php

/**
 * BaseSaturdaysBreakfastProgram
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $hour
 * @property string $place
 * @property string $content
 * @property Doctrine_Collection $SaturdaysBreakfastSpeaker
 * 
 * @method date                      getHour()                      Returns the current record's "hour" value
 * @method string                    getPlace()                     Returns the current record's "place" value
 * @method string                    getContent()                   Returns the current record's "content" value
 * @method Doctrine_Collection       getSaturdaysBreakfastSpeaker() Returns the current record's "SaturdaysBreakfastSpeaker" collection
 * @method SaturdaysBreakfastProgram setHour()                      Sets the current record's "hour" value
 * @method SaturdaysBreakfastProgram setPlace()                     Sets the current record's "place" value
 * @method SaturdaysBreakfastProgram setContent()                   Sets the current record's "content" value
 * @method SaturdaysBreakfastProgram setSaturdaysBreakfastSpeaker() Sets the current record's "SaturdaysBreakfastSpeaker" collection
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSaturdaysBreakfastProgram extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('saturdays_breakfast_program');
        $this->hasColumn('hour', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('place', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SaturdaysBreakfastSpeaker', array(
             'local' => 'id',
             'foreign' => 'saturdays_breakfast_program_id'));
    }
}