<?php

/**
 * BaseUserAreaAccommodation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $place
 * @property integer $image_id
 * @property string $content
 * @property integer $order_nr
 * @property Image $Image
 * 
 * @method string                getPlace()    Returns the current record's "place" value
 * @method integer               getImageId()  Returns the current record's "image_id" value
 * @method string                getContent()  Returns the current record's "content" value
 * @method integer               getOrderNr()  Returns the current record's "order_nr" value
 * @method Image                 getImage()    Returns the current record's "Image" value
 * @method UserAreaAccommodation setPlace()    Sets the current record's "place" value
 * @method UserAreaAccommodation setImageId()  Sets the current record's "image_id" value
 * @method UserAreaAccommodation setContent()  Sets the current record's "content" value
 * @method UserAreaAccommodation setOrderNr()  Sets the current record's "order_nr" value
 * @method UserAreaAccommodation setImage()    Sets the current record's "Image" value
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserAreaAccommodation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_area_accommodation');
        $this->hasColumn('place', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('image_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('order_nr', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Image', array(
             'local' => 'image_id',
             'foreign' => 'id'));
    }
}