<?php

/**
 * BaseStaticContentSubpage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $menu_category_id
 * @property integer $subpage_id
 * @property string $name
 * @property string $title
 * @property string $content
 * @property MenuCategory $MenuCategory
 * @property Subpage $Subpage
 * 
 * @method integer              getMenuCategoryId()   Returns the current record's "menu_category_id" value
 * @method integer              getSubpageId()        Returns the current record's "subpage_id" value
 * @method string               getName()             Returns the current record's "name" value
 * @method string               getTitle()            Returns the current record's "title" value
 * @method string               getContent()          Returns the current record's "content" value
 * @method MenuCategory         getMenuCategory()     Returns the current record's "MenuCategory" value
 * @method Subpage              getSubpage()          Returns the current record's "Subpage" value
 * @method StaticContentSubpage setMenuCategoryId()   Sets the current record's "menu_category_id" value
 * @method StaticContentSubpage setSubpageId()        Sets the current record's "subpage_id" value
 * @method StaticContentSubpage setName()             Sets the current record's "name" value
 * @method StaticContentSubpage setTitle()            Sets the current record's "title" value
 * @method StaticContentSubpage setContent()          Sets the current record's "content" value
 * @method StaticContentSubpage setMenuCategory()     Sets the current record's "MenuCategory" value
 * @method StaticContentSubpage setSubpage()          Sets the current record's "Subpage" value
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStaticContentSubpage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('static_content_subpage');
        $this->hasColumn('menu_category_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('subpage_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('title', 'string', 512, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 512,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MenuCategory', array(
             'local' => 'menu_category_id',
             'foreign' => 'id'));

        $this->hasOne('Subpage', array(
             'local' => 'subpage_id',
             'foreign' => 'id'));
    }
}