<?php

/**
 * BaseSaturdaysBreakfastSpeaker
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $saturdays_breakfast_program_id
 * @property integer $saturdays_breakfast_speaker_image_id
 * @property string $content
 * @property integer $order_nr
 * @property SaturdaysBreakfastProgram $SaturdaysBreakfastProgram
 * @property SaturdaysBreakfastSpeakerImage $SaturdaysBreakfastSpeakerImage
 * 
 * @method integer                        getSaturdaysBreakfastProgramId()          Returns the current record's "saturdays_breakfast_program_id" value
 * @method integer                        getSaturdaysBreakfastSpeakerImageId()     Returns the current record's "saturdays_breakfast_speaker_image_id" value
 * @method string                         getContent()                              Returns the current record's "content" value
 * @method integer                        getOrderNr()                              Returns the current record's "order_nr" value
 * @method SaturdaysBreakfastProgram      getSaturdaysBreakfastProgram()            Returns the current record's "SaturdaysBreakfastProgram" value
 * @method SaturdaysBreakfastSpeakerImage getSaturdaysBreakfastSpeakerImage()       Returns the current record's "SaturdaysBreakfastSpeakerImage" value
 * @method SaturdaysBreakfastSpeaker      setSaturdaysBreakfastProgramId()          Sets the current record's "saturdays_breakfast_program_id" value
 * @method SaturdaysBreakfastSpeaker      setSaturdaysBreakfastSpeakerImageId()     Sets the current record's "saturdays_breakfast_speaker_image_id" value
 * @method SaturdaysBreakfastSpeaker      setContent()                              Sets the current record's "content" value
 * @method SaturdaysBreakfastSpeaker      setOrderNr()                              Sets the current record's "order_nr" value
 * @method SaturdaysBreakfastSpeaker      setSaturdaysBreakfastProgram()            Sets the current record's "SaturdaysBreakfastProgram" value
 * @method SaturdaysBreakfastSpeaker      setSaturdaysBreakfastSpeakerImage()       Sets the current record's "SaturdaysBreakfastSpeakerImage" value
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSaturdaysBreakfastSpeaker extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('saturdays_breakfast_speaker');
        $this->hasColumn('saturdays_breakfast_program_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('saturdays_breakfast_speaker_image_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('order_nr', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SaturdaysBreakfastProgram', array(
             'local' => 'saturdays_breakfast_program_id',
             'foreign' => 'id'));

        $this->hasOne('SaturdaysBreakfastSpeakerImage', array(
             'local' => 'saturdays_breakfast_speaker_image_id',
             'foreign' => 'id'));
    }
}