<?php

/**
 * BaseSubpage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $menu_category_id
 * @property string $name
 * @property boolean $is_menu
 * @property boolean $is_module
 * @property MenuCategory $MenuCategory
 * @property Doctrine_Collection $StaticContentSubpage
 * 
 * @method integer             getMenuCategoryId()       Returns the current record's "menu_category_id" value
 * @method string              getName()                 Returns the current record's "name" value
 * @method boolean             getIsMenu()               Returns the current record's "is_menu" value
 * @method boolean             getIsModule()             Returns the current record's "is_module" value
 * @method MenuCategory        getMenuCategory()         Returns the current record's "MenuCategory" value
 * @method Doctrine_Collection getStaticContentSubpage() Returns the current record's "StaticContentSubpage" collection
 * @method Subpage             setMenuCategoryId()       Sets the current record's "menu_category_id" value
 * @method Subpage             setName()                 Sets the current record's "name" value
 * @method Subpage             setIsMenu()               Sets the current record's "is_menu" value
 * @method Subpage             setIsModule()             Sets the current record's "is_module" value
 * @method Subpage             setMenuCategory()         Sets the current record's "MenuCategory" value
 * @method Subpage             setStaticContentSubpage() Sets the current record's "StaticContentSubpage" collection
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubpage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subpage');
        $this->hasColumn('menu_category_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 120, array(
             'type' => 'string',
             'unique' => true,
             'length' => 120,
             ));
        $this->hasColumn('is_menu', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('is_module', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MenuCategory', array(
             'local' => 'menu_category_id',
             'foreign' => 'id'));

        $this->hasMany('StaticContentSubpage', array(
             'local' => 'id',
             'foreign' => 'subpage_id'));
    }
}