<?php

/**
 * BaseConferenceProgram
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $day
 * @property date $hour
 * @property string $place
 * @property string $content
 * @property Doctrine_Collection $ConferenceSpeaker
 * 
 * @method date                getDay()               Returns the current record's "day" value
 * @method date                getHour()              Returns the current record's "hour" value
 * @method string              getPlace()             Returns the current record's "place" value
 * @method string              getContent()           Returns the current record's "content" value
 * @method Doctrine_Collection getConferenceSpeaker() Returns the current record's "ConferenceSpeaker" collection
 * @method ConferenceProgram   setDay()               Sets the current record's "day" value
 * @method ConferenceProgram   setHour()              Sets the current record's "hour" value
 * @method ConferenceProgram   setPlace()             Sets the current record's "place" value
 * @method ConferenceProgram   setContent()           Sets the current record's "content" value
 * @method ConferenceProgram   setConferenceSpeaker() Sets the current record's "ConferenceSpeaker" collection
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConferenceProgram extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('conference_program');
        $this->hasColumn('day', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('hour', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('place', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ConferenceSpeaker', array(
             'local' => 'id',
             'foreign' => 'conference_program_id'));
    }
}