<?php

/**
 * BaseFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $filename
 * @property integer $filesize
 * @property string $filetype
 * 
 * @method string  getFilename() Returns the current record's "filename" value
 * @method integer getFilesize() Returns the current record's "filesize" value
 * @method string  getFiletype() Returns the current record's "filetype" value
 * @method File    setFilename() Sets the current record's "filename" value
 * @method File    setFilesize() Sets the current record's "filesize" value
 * @method File    setFiletype() Sets the current record's "filetype" value
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('file');
        $this->hasColumn('filename', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('filesize', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('filetype', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}