<?php

/**
 * BasePicnicParticipantImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $filename
 * @property Doctrine_Collection $PicnicParticipant
 * 
 * @method string                 getFilename()          Returns the current record's "filename" value
 * @method Doctrine_Collection    getPicnicParticipant() Returns the current record's "PicnicParticipant" collection
 * @method PicnicParticipantImage setFilename()          Sets the current record's "filename" value
 * @method PicnicParticipantImage setPicnicParticipant() Sets the current record's "PicnicParticipant" collection
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePicnicParticipantImage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('picnic_participant_image');
        $this->hasColumn('filename', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PicnicParticipant', array(
             'local' => 'id',
             'foreign' => 'picnic_participant_image_id'));
    }
}