<?php

/**
 * BaseArchiveExhibitionVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $archive_id
 * @property integer $video_id
 * @property integer $order_nr
 * @property string $content
 * @property Archive $Archive
 * @property Video $Video
 * 
 * @method integer                getArchiveId()  Returns the current record's "archive_id" value
 * @method integer                getVideoId()    Returns the current record's "video_id" value
 * @method integer                getOrderNr()    Returns the current record's "order_nr" value
 * @method string                 getContent()    Returns the current record's "content" value
 * @method Archive                getArchive()    Returns the current record's "Archive" value
 * @method Video                  getVideo()      Returns the current record's "Video" value
 * @method ArchiveExhibitionVideo setArchiveId()  Sets the current record's "archive_id" value
 * @method ArchiveExhibitionVideo setVideoId()    Sets the current record's "video_id" value
 * @method ArchiveExhibitionVideo setOrderNr()    Sets the current record's "order_nr" value
 * @method ArchiveExhibitionVideo setContent()    Sets the current record's "content" value
 * @method ArchiveExhibitionVideo setArchive()    Sets the current record's "Archive" value
 * @method ArchiveExhibitionVideo setVideo()      Sets the current record's "Video" value
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArchiveExhibitionVideo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('archive_exhibition_video');
        $this->hasColumn('archive_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('video_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
        $this->hasColumn('order_nr', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Archive', array(
             'local' => 'archive_id',
             'foreign' => 'id'));

        $this->hasOne('Video', array(
             'local' => 'video_id',
             'foreign' => 'id'));
    }
}