<?php

/**
 * BaseConcertProgram
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $day
 * @property date $hour
 * @property string $place
 * @property string $content
 * @property integer $image_id
 * @property Image $Image
 * 
 * @method date           getDay()      Returns the current record's "day" value
 * @method date           getHour()     Returns the current record's "hour" value
 * @method string         getPlace()    Returns the current record's "place" value
 * @method string         getContent()  Returns the current record's "content" value
 * @method integer        getImageId()  Returns the current record's "image_id" value
 * @method Image          getImage()    Returns the current record's "Image" value
 * @method ConcertProgram setDay()      Sets the current record's "day" value
 * @method ConcertProgram setHour()     Sets the current record's "hour" value
 * @method ConcertProgram setPlace()    Sets the current record's "place" value
 * @method ConcertProgram setContent()  Sets the current record's "content" value
 * @method ConcertProgram setImageId()  Sets the current record's "image_id" value
 * @method ConcertProgram setImage()    Sets the current record's "Image" value
 * 
 * @package    ofip
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConcertProgram extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('concert_program');
        $this->hasColumn('day', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('hour', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('place', 'string', 120, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 120,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('image_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Image', array(
             'local' => 'image_id',
             'foreign' => 'id'));
    }
}