<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/15 11:51:25

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ofip',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
