<?php

/**
 * ArchiveExhibitionAudioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchiveExhibitionAudioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArchiveExhibitionAudioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArchiveExhibitionAudio');
    }
}