<?php

/**
 * ArchiveExhibitionImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchiveExhibitionImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArchiveExhibitionImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArchiveExhibitionImage');
    }
}