<?php

/**
 * ArchiveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchiveTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArchiveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Archive');
    }
}