<?php

/**
 * ArchiveGalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArchiveGalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArchiveGalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArchiveGallery');
    }
}