<?php

/**
 * CafeteriaProgramTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CafeteriaProgramTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CafeteriaProgramTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CafeteriaProgram');
    }
}