<?php

/**
 * ConcertProgramTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConcertProgramTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConcertProgramTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConcertProgram');
    }
}