<?php

/**
 * ConferenceSpeakerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConferenceSpeakerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConferenceSpeakerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConferenceSpeaker');
    }
}