<?php

/**
 * ConferenceProgramTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConferenceProgramTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConferenceProgramTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConferenceProgram');
    }
}