<?php

/**
 * HomepageBoxesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HomepageBoxesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HomepageBoxesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HomepageBoxes');
    }
}