<?php

/**
 * LayoutImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LayoutImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LayoutImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LayoutImage');
    }
}