<?php

/**
 * LogotypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogotypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogotypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Logotype');
    }
}