<?php

/**
 * PicnicPlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PicnicPlanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PicnicPlanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PicnicPlan');
    }
}