<?php

/**
 * PicnicProgramTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PicnicProgramTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PicnicProgramTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PicnicProgram');
    }
}