<?php

/**
 * PicnicParticipantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PicnicParticipantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PicnicParticipantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PicnicParticipant');
    }
}