<?php

/**
 * PicnicParticipantImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PicnicParticipantImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PicnicParticipantImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PicnicParticipantImage');
    }
}