<?php

/**
 * RegistrationFormTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegistrationFormTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegistrationFormTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RegistrationForm');
    }
}