<?php

/**
 * SaturdaysBreakfastSpeakerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SaturdaysBreakfastSpeakerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SaturdaysBreakfastSpeakerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SaturdaysBreakfastSpeaker');
    }
}