<?php

/**
 * SaturdaysBreakfastProgramTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SaturdaysBreakfastProgramTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SaturdaysBreakfastProgramTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SaturdaysBreakfastProgram');
    }
}