<?php

/**
 * SaturdaysBreakfastSpeakerImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SaturdaysBreakfastSpeakerImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SaturdaysBreakfastSpeakerImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SaturdaysBreakfastSpeakerImage');
    }
}