<?php

/**
 * SpeakerImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpeakerImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpeakerImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SpeakerImage');
    }
}