<?php

/**
 * StaticContentGlobalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StaticContentGlobalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StaticContentGlobalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StaticContentGlobal');
    }
}