<?php

/**
 * StaticContentSubpageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StaticContentSubpageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StaticContentSubpageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StaticContentSubpage');
    }
}