<?php

/**
 * SubpageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubpageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubpageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subpage');
    }
}