<?php

/**
 * UserAreaPlaceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserAreaPlaceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserAreaPlaceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserAreaPlace');
    }
}