<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/18 18:25:15

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=sql.lechst.nazwa.pl;dbname=lechst_4',
  'username' => 'lechst_4',
  'password' => 'PI314159265chuj',
  'attributes' => 
  array (
    'DEFAULT_TABLE_COLLATE' => 'utf8_polish_ci',
  ),
  'name' => 'doctrine',
)),);
