<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/13 19:01:36

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ofip',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
