<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/07/13 16:48:42
sfConfig::add(array(
  'mod_static_content_global_enabled' => true,
  'mod_static_content_global_view_class' => 'sfPHP',
));
