<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/07/16 22:29:55
sfConfig::add(array(
  'mod_homepage_boxes_enabled' => true,
  'mod_homepage_boxes_view_class' => 'sfPHP',
));
