<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/07/13 17:56:41
sfConfig::add(array(
  'mod_registration_form_enabled' => true,
  'mod_registration_form_view_class' => 'sfPHP',
));
