<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/07/18 13:02:04
sfConfig::add(array(
  'mod_homepage_boxes_enabled' => true,
  'mod_homepage_boxes_view_class' => 'sfPHP',
));
