<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/07/13 17:07:09
sfConfig::add(array(
  'mod_archive_gallery_enabled' => true,
  'mod_archive_gallery_view_class' => 'sfPHP',
));
