all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=ofip'
      username: root
      password: null
      
      attributes:
        DEFAULT_TABLE_COLLATE: utf8_polish_ci
