<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/18 13:09:29

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ofip',
  'username' => 'ofip',
  'password' => 'ofip',
  'attributes' => 
  array (
    'DEFAULT_TABLE_COLLATE' => 'utf8_polish_ci',
  ),
  'name' => 'doctrine',
)),);
