<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/07/18 13:10:24
sfConfig::add(array(
  'mod_static_content_subpage_enabled' => true,
  'mod_static_content_subpage_view_class' => 'sfPHP',
));
