detect_relations:             true

MenuCategory:
  columns:
    name:                     {type: string(120), notnull: true, unique: true}
    order_nr:                 {type: integer, unique: true}

StaticContentGlobal:
  columns:
    name:                     {type: string(120), notnull: true}
    title:                    {type: string(512), notnull: true}
    content:                  {type: string, notnull: true}

HomepageBoxes:
  columns:
    container_nr:             {type: integer, notnull: true}
    menu_category_id: ~
    is_active:                {type: boolean, default: false}
    title:                    {type: string(512), notnull: true}
    content:                  {type: string, notnull: true}
    image_id: ~

LayoutImage:
  columns:
    filename:                 {type: string(120), notnull: true}
    order_nr:                 {type: integer, notnull: true}

Logotype:
  columns:
    filename:                 {type: string(120), notnull: true}

File:
  columns:
    filename:                 {type: string(120), notnull: true}
    filesize:                 {type: integer, notnull: true}
    filetype:                 {type: string(120), notnull: true}

Image:
  columns:
    filename:                 {type: string(120), notnull: true}

Video:
  columns:
    filename:                 {type: string(120), notnull: true}

Audio:
  columns:
    filename:                 {type: string(120), notnull: true}

Subpage:
  columns:
    menu_category_id: ~
    name:                     {type: string(120), unique: true}
    is_menu:                  {type: boolean, notnull: true}
    is_module:                {type: boolean, default: false}
    module:                   {type: string(120), notnull: true}

StaticContentSubpage:
  columns:
    menu_category_id: ~
    subpage_id: ~
    name:                     {type: string(120), notnull: true}
    title:                    {type: string(512), notnull: true}
    content:                  {type: string, notnull: true}

Archive:
  columns:
    edition:                  {type: string(4)}
    link_to:                  {type: string}
    image_id: ~

ArchiveGallery:    
  columns:
    archive_id: ~
    image_id: ~
    order_nr:                 {type: integer, notnull: true}
    content:                  {type: string, notnull: true}

ArchiveExhibitionImage:
  columns:
    archive_id: ~
    image_id: ~
    order_nr:                 {type: integer, notnull: true}
    content:                  {type: string, notnull: true}

ArchiveExhibitionVideo:
  columns:
    archive_id: ~
    video_id: ~
    order_nr:                 {type: integer, notnull: true}
    content:                  {type: string, notnull: true}

ArchiveExhibitionAudio:
  columns:
    archive_id: ~
    audio_id: ~
    order_nr:                 {type: integer, notnull: true}
    content:                  {type: string, notnull: true}

ConferenceProgram:
  columns:
    day:                      {type: date, notnull: true}
    hour:                     {type: date, notnull: true}
    place:                    {type: string(120), notnull: true}
    content:                  {type: string, notnull: true}

SpeakerImage:
  columns:
    filename:                 {type: string(120), notnull: true}

ConferenceSpeaker:
  columns:
    conference_program_id: ~
    speaker_image_id: ~
    content:                  {type: string, notnull: true}
    order_nr:                 {type: integer, notnull: true}

UserAreaPlace:
  columns:
    place:                    {type: string(120), notnull: true}
    content:                  {type: string, notnull: true}

UserAreaAccommodation:
  columns:
    place:                    {type: string(120), notnull: true}
    image_id: ~
    content:                  {type: string, notnull: true}
    order_nr:                 {type: integer, notnull: true}

UserAreaUserImage:
  columns:
    filename:                 {type: string(120), notnull: true}

UserAreaUsers:
  columns:
    user_area_user_image_id: ~
    content:                  {type: string, notnull: true}
    order_nr:                 {type: integer, notnull: true}

SaturdaysBreakfastProgram:
  columns:
    hour:                     {type: date, notnull: true}
    place:                    {type: string(120), notnull: true}
    content:                  {type: string, notnull: true}

SaturdaysBreakfastSpeakerImage:
  columns:
    filename:                 {type: string(120), notnull: true}

SaturdaysBreakfastSpeaker:
  columns:
    saturdays_breakfast_program_id: ~
    saturdays_breakfast_speaker_image_id: ~
    content:                  {type: string, notnull: true}   
    order_nr:                 {type: integer, notnull: true}

CafeteriaProgram:
  columns:
    day:                      {type: date, notnull: true}
    hour:                     {type: date, notnull: true}
    place:                    {type: string(120), notnull: true}
    content:                  {type: string, notnull: true}
    image_id: ~

SpectacleProgram:
  columns:
    day:                      {type: date, notnull: true}
    hour:                     {type: date, notnull: true}
    place:                    {type: string(120), notnull: true}
    content:                  {type: string, notnull: true}
    image_id: ~

ConcertProgram:
  columns:
    day:                      {type: date, notnull: true}
    hour:                     {type: date, notnull: true}
    place:                    {type: string(120), notnull: true}
    content:                  {type: string, notnull: true}
    image_id: ~

Exhibitions:
  columns:
    name:                     {type: string(120), notnull: true}
    link_to:                  {type: string}
    image_id: ~

Calendar:
  columns:
    event:                    {type: string(120), notnull: true}
    day:                      {type: date, notnull: true}
    hour:                     {type: date, notnull: true}
    place:                    {type: string(120), notnull: true}
    content:                  {type: string, notnull: true}
    image_id: ~

PicnicPlan:
  columns:
    name:                     {type: string(120), notnull: true}
    place:                    {type: string(120), notnull: true}
    content:                  {type: string, notnull: true}
    image_id: ~
    
PicnicProgram:
  columns:
    hour:                     {type: date, notnull: true}
    place:                    {type: string(120), notnull: true}
    content:                  {type: string, notnull: true}

PicnicParticipantImage:
  columns:
    filename:                 {type: string(120), notnull: true}

PicnicParticipant:
  columns:
    picnic_participant_image_id: ~
    content:                  {type: string, notnull: true}
    order_nr:                 {type: integer, notnull: true}
    
RegistrationForm:
  columns:
    name:                     {type: string(120)}
    my_email:                 {type: string(120), email: true, notnull: true}
    organization_name:        {type: string(120)}
    street:                   {type: string(120)}
    postal_code:              {type: string(120)}
    locality:                 {type: string(120)}
    voivodeship:              {type: string(120)}
    phone_number:             {type: string(120)}
    fax:                      {type: string(120),}
    organization_email:       {type: string(120), email: true}
    internet_page:            {type: string}
    NIP:                      {type: string(15)}
    agreement1:               {type: boolean, default: false}
    fee_number:               {type: integer}
    fac_name:                 {type: string(120)}
    fac_address:              {type: string(120)}
    fac_NIP:                  {type: string(120)}
    accommodation:            {type: boolean, default: false}
    participation1:          {type: boolean, default: false}
    participation2:          {type: boolean, default: false}
    participation3:          {type: boolean, default: false}
    participation4:          {type: boolean, default: false}
    participation5:          {type: boolean, default: false}
    participation6:          {type: boolean, default: false}
    participation7:          {type: boolean, default: false}
    participation8:          {type: boolean, default: false}
    participation9:          {type: boolean, default: false}
    participation10:         {type: boolean, default: false}
    participation11:         {type: boolean, default: false}
    participation12:         {type: boolean, default: false}
    participation13:         {type: boolean, default: false}
    participation14:         {type: boolean, default: false}
    participation15:         {type: boolean, default: false}
    agreement2:               {type: boolean, default: false}
